Module_A3:
  model: Razumdom_DRM88R
  description: Управление оборудованием 230V
  unit_id: 3
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x4'
    - '0x15'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x7'
    - '0x4'
    - '0x16'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x7'
    - '0x4'
    - '0x17'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x7'
    - '0x4'
    - '0x19'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x5'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x7'
    - '0x4'
    - '0x1a'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x6'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x7'
    - '0x4'
    - '0x1b'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x7'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A4:
  model: Razumdom_DRM21R
  description: Питание кондиционера в прихожей
  unit_id: 4
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x3'
    - '0xa'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A5:
  model: Razumdom_DRM21R
  description: Питание кондиционера в гостинной
  unit_id: 5
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x3'
    - '0xa'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A6:
  model: Razumdom_DRM21R
  description: Питание бойлера
  unit_id: 6
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x3'
    - '0xa'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A8:
  model: Razumdom_DRM88R
  description: Управление оборудованием 24V
  unit_id: 8
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x4'
    - '0x15'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x2'
    - '0x3'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x1'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
    - '0x4'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x2'
    - '0x2'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x7'
    - '0x4'
    - '0x17'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x2'
    - '0x3'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x7'
    - '0x4'
    - '0x18'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x4'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x4'
    - '0x2d'
    - '0x0'
    - '0x1'
    - '0x5'
    - '0x2'
    - '0x5'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A9:
  model: Razumdom_DDL88R
  description: Диммер подсветки прихожей и предбанника
  unit_id: 9
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x2'
    - '0x2'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x4'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A10:
  model: Razumdom_DDL88R
  description: Диммер подсветки кухонного гарнитура
  unit_id: 10
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x0'
    - '0x3'
    - '0xa'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x7'
    - '0x2'
    - '0x1'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x7'
    - '0x2'
    - '0x1'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x7'
    - '0x2'
    - '0x1'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x7'
    - '0x2'
    - '0x1'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x4'
    - '0x0'
    - '0x1'
    - '0x2'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
Module_A11:
  model: Razumdom_DDL88R
  description: Диммер подсветки детской
  unit_id: 11
  baud_rate: 115200
  parity: N
  stop_bits: 1
  scenarios:
  - Сценарий 0:
    - '0x7'
    - '0x3'
    - '0xa'
    - '0x0'
    - '0x0'
    - '0x1'
    - '0x1'
    - '0x1'
    - '0x0'
    - '0x1'
    - '0x3'
    - '0x0'
    - '0x0'
  - Сценарий 1:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 2:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 3:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 4:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 5:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 6:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
  - Сценарий 7:
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
    - '0x0'
